// Barrel for the typed query helpers. Import like:
//   import { getClients, sendMessage } from "@/lib/db/queries"
export * as professionalsQ from "./professionals"
export * as clientsQ from "./clients"
export * as leadsQ from "./leads"
export * as messagesQ from "./messages"
export * as notificationsQ from "./notifications"
export * as appointmentsQ from "./appointments"
export * as formsQ from "./forms"
export * as documentsQ from "./documents"
export * as invoicesQ from "./invoices"
export * as microSitesQ from "./micro-sites"
